### PR TITLE
Make `with` necessary when declaring type invariants.

### LINKED ISSUE #369: `with` is optional for type invariants
Gospel parser allows for:
```ocaml
type t
(*@ invariant ... *)
```
and
```ocaml
type t
(*@ with x invariant ... *)
```
Is the first form necessary?
My feeling is that without naming a value of type `t`, there is not much content to give to a type invariant. But maybe I am missing something?

This then make the identifier optional in the AST, hence an additional layer of destruction (so to speak) when exploring a type specification and a decision to make about what to do when there is no name (which is useless work if this never happen, and hard to do without having an idea of a potential use case).

Also, I believe the documentation is not up to date: https://github.com/ocaml-gospel/gospel/blob/main/docs/docs/language/type-specifications.md?plain=1#L33

### PR DESCRIPTION
**Pull request by n-osborne**
Fixes #369

### CODE REVIEW

**Review by shym — APPROVED** [review]
LGTM, well done!
It requires a round of `dune runtest --auto-promote` or two before merging.
A small suggestion: it might be nicer in `src/upretty_printer.ml` to reset `Option` with a `module Option = Stdlib.Option` just after the `open`s, since we don’t really need `Opprintast.Option` anyway.

**Comment by n-osborne** [comment]
Thanks.
I've followed your suggestion and updated the documentation to reflect the change.

**Review by shym — APPROVED** [review]
I pushed 2 mini-fixes. They should be squashed and this is good to merge for me!

**Comment by n-osborne** [comment]
CI failure is unrelated.
I merge.

**Pull request merged**
