### PR TITLE
Implement pattern matching exhaustive test

### PR DESCRIPTION
**Pull request by paulpatault**

### CODE REVIEW

**Comment by pascutto** [comment]
Thanks! It's not ready yet, but we'll let you know!

**Comment by pascutto** [comment]
@mariojppereira I think you could review it if you still want to :)

**Comment by mariojppereira** [comment]
Sure I do :D

**Comment by pascutto** [comment]
Thanks. On my end I'm rebasing this to main and adapting for #195 too.

**Pull request merged**
