### PR TITLE
Update to the Documentation Site

### PR DESCRIPTION
**Pull request by mrjazzybread**
Hello

I  was analyzing the Gospel documentation website and as I was exploring, I noticed that there was a small discrepancy: we state that the type checker differentiates between terms and formulae when that is not the case anymore. Additionally, there were some outdated node packages which led to security problems. I figured that these two issues were relevant enough that they warranted a small PR to fix them. I also changed the git hub actions to use an updated version of node.

### CODE REVIEW

**Review by n-osborne — COMMENTED** [review]
Thanks!

- First commit message: Updated -> Update
- The second commit contains an update of node version while it is about updating the content of the documentation

I haven't investigated the incompatibility reported by the CI when trying to build the documentation.

Apart from that, I obviously agree with the change.

**Comment by mrjazzybread** [comment]
Ok I fixed the issues you pointed out. With regards to  incompatibility, I think if you change the node version on the Gospel side it will work.

**Comment by n-osborne** [comment]
It seems that if you update the `.github/workflows/documentation.yml` the same way you've changed the `.github/workflows/localdoc.yml`, it should work. (I couldn't reproduce though).

Regarding [1b15126](https://github.com/ocaml-gospel/gospel/pull/425/commits/1b151260db7967e332271e88b8771943ad154722), it is cleaner to use `git rebase` in these cases, no need for a merge commit.

**Comment by mrjazzybread** [comment]
Ok, I fixed the merge commit and changed the node version on the `github/workflows/documentation.yml` file.

**Comment by n-osborne** [comment]
Excellent! Thank you!

**Pull request merged**
